export const siteData = {
  brand: "Doçura da Fazenda",
  location: "Cambuí, Minas Gerais",
  whatsappLabel: "Fale conosco",
  whatsappUrl: "https://wa.me/553534316838",
  phone: "(35) 3431-6838",
  email: "Atendimento pelo WhatsApp",
  address: "Rod. Fernão Dias, 894, Cambuí - MG, 37600-000",
  mapEmbed:
    "https://maps.google.com/maps?q=Emp%C3%B3rio%20-%20Do%C3%A7ura%20Da%20Fazenda%2C%20Rod.%20Fern%C3%A3o%20Dias%2C%20894%2C%20Cambu%C3%AD%20-%20MG%2C%2037600-000&t=m&z=15&output=embed&iwloc=near",
  nav: [
    { label: "Início", href: "/" },
    { label: "Produtos", href: "/products" },
    { label: "Sobre nós", href: "/about" },
    { label: "Contato", href: "/contact" },
  ],
  heroSlides: [
    {
      title: "O verdadeiro sabor do doce de leite mineiro",
      body:
        "Uma receita de família feita com paciência, tradição e ingredientes selecionados com cuidado.",
      video: "/assets/videos/bg-principal-1-com-vaquinha.mp4",
    },
    {
      title: "Sabor que carrega tradição",
      body:
        "Cada produção preserva a textura marcante e o sabor inconfundível do autêntico doce de leite artesanal.",
      video: "/assets/videos/bg-principal-1-com-vaquinha.mp4",
    },
  ],
  heroBanners: [
    {
      eyebrow: "Desde 1998 • Cambuí, Minas Gerais",
      title: "O verdadeiro sabor do doce de leite mineiro.",
      body:
        "Produção familiar, textura cremosa e ingredientes selecionados para preservar o sabor autêntico que acompanha a mesa mineira.",
      cta: "Conheça os produtos",
      href: "/products",
      mediaType: "image",
      media: "/assets/images/emporio-1-1280x860-1.jpeg",
      fallback: "/assets/images/emporio-1-1280x860-1.jpeg",
      product: "/assets/images/img-docepastoso.png",
    },
    {
      eyebrow: "Receita tradicional",
      title: "Sabor que carrega tradição.",
      body:
        "Doce de leite pastoso, barras e tabletes feitos com cuidado artesanal e padrão de qualidade para todos os momentos.",
      cta: "Ver linha completa",
      href: "/products",
      mediaType: "image",
      media: "/assets/images/emporio-0-1280x860-1.jpeg",
      product: "/assets/images/caramelo.png",
    },
    {
      eyebrow: "Empório em Cambuí",
      title: "Uma parada mineira na Fernão Dias.",
      body:
        "Além dos doces, o empório reúne produtos regionais e atendimento acolhedor às margens da Rodovia Fernão Dias.",
      cta: "Nossa localização",
      href: "/contact",
      mediaType: "image",
      media: "/assets/images/emporio-1-1280x860-1.jpeg",
      product: "/assets/images/caramelo-macchiato.png",
    },
  ],
  about: {
    eyebrow: "Sobre nós",
    title: "Qualidade e sabor em cada detalhe",
    body:
      "A Doçura da Fazenda é uma empresa familiar mineira que transforma tradição em sabor desde 1998. Com produção artesanal, ingredientes selecionados e compromisso com a qualidade, levamos aos nossos clientes o verdadeiro doce de leite mineiro, feito com carinho e dedicação.",
    bullets: [
      "Mais de duas décadas de história, tradição e evolução constante.",
      "Produção que preserva o sabor autêntico do doce de leite mineiro.",
      "Produtos fabricados com cuidado, padrão e confiança.",
    ],
    pillars: [
      {
        title: "Receita tradicional",
        body: "O autêntico doce de leite mineiro feito com história, cuidado e dedicação.",
        image: "/assets/images/receita.png",
      },
      {
        title: "Melhores ingredientes",
        body: "Matérias-primas escolhidas com cuidado para garantir mais sabor e qualidade.",
        image: "/assets/images/farinha.png",
      },
      {
        title: "Sabor que encanta",
        body: "Um doce de leite marcante, feito para conquistar todos os paladares.",
        image: "/assets/images/caramelo.png",
      },
      {
        title: "Preparado com carinho",
        body: "Mais do que um produto, um sabor especial feito para criar boas memórias.",
        image: "/assets/images/caramelo-macchiato.png",
      },
    ],
  },
  productsIntro: {
    title: "Conheça a nossa linha de produtos",
    body:
      "Doce de leite pastoso, tabletes, barras e versões sortidas produzidos com qualidade, tradição e o verdadeiro sabor mineiro.",
  },
  productCategories: [
    {
      name: "Barra",
      slug: "barra",
      description: "Tabletes de 400 g com sabores tradicionais e combinações especiais.",
      image: "/assets/images/products/categoria-barra.png",
    },
    {
      name: "Pastoso",
      slug: "pastoso",
      description: "Doce de leite cremoso em potes, ideal para mesa, receitas e presentes.",
      image: "/assets/images/products/categoria-pastoso.png",
    },
    {
      name: "Display",
      slug: "display",
      description: "Displays de 1 kg e potes com unidades individuais para revenda.",
      image: "/assets/images/products/categoria-display.png",
    },
  ],
  products: [
    {
      name: "Display de Doce de Leite com Ameixa 1 kg",
      slug: "display-de-doce-de-leite-com-ameixa-1-kg",
      category: "Display",
      size: "1 kg",
      description: "Display com doce de leite e ameixa, pensado para exposição, venda assistida e giro no balcão.",
      image: "/assets/images/products/Display-Doce-de-Leite-com-Ameixa.png",
    },
    {
      name: "Display Cocada - Doce de Leite com Coco 1 kg",
      slug: "display-cocada-doce-de-leite-com-coco-1-kg",
      category: "Display",
      size: "1 kg",
      description: "Display de cocada com doce de leite e coco, com sabor marcante para revendas e empórios.",
      image: "/assets/images/products/Display-doce-de-Leite-Cocada.png",
    },
    {
      name: "Display de Doce de Leite com Amendoim 1 kg",
      slug: "display-de-doce-de-leite-com-amendoim-1-kg",
      category: "Display",
      size: "1 kg",
      description: "Display de doce de leite com amendoim, uma opção de venda prática e cheia de textura.",
      image: "/assets/images/products/Display-Doce-de-Leite-com-Amendoim.png",
    },
    {
      name: "Display de Doce de Leite Tradicional 1 kg",
      slug: "display-de-doce-de-leite-tradicional-1-kg",
      category: "Display",
      size: "1 kg",
      description: "Display tradicional com o sabor clássico do doce de leite mineiro para ponto de venda.",
      image: "/assets/images/products/Display-Doce-de-Leite-Tradicional.png",
    },
    {
      name: "Potes Cocada - Doce de Leite com Coco c/20 un. 50 g",
      slug: "potes-cocada-doce-de-leite-com-coco-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50 g",
      description: "Pote com tabletes individuais de cocada com doce de leite e coco, ideal para revenda.",
      image: "/assets/images/products/Pote-de-Tabletes-de-Cocada.png",
    },
    {
      name: "Potes Doce de Leite com Amendoim c/20 un. 50 g",
      slug: "potes-doce-de-leite-com-amendoim-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50 g",
      description: "Pote com unidades individuais de doce de leite com amendoim para balcões e empórios.",
      image: "/assets/images/products/Pote-de-Tablete-de-Doce-de-Leite-com-Amendoim.png",
    },
    {
      name: "Potes Doce de Leite com Ameixa c/20 un. 50 g",
      slug: "potes-doce-de-leite-com-ameixa-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50 g",
      description: "Pote com tabletes de doce de leite com ameixa em porções individuais.",
      image: "/assets/images/products/Pote-de-Tablete-de-Doce-de-Leite-com-Ameixa.png",
    },
    {
      name: "Pote Doce de Leite Tradicional c/20 un. 50 g",
      slug: "pote-doce-de-leite-tradicional-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50 g",
      description: "Pote com tabletes tradicionais de doce de leite, prontos para exposição e revenda.",
      image: "/assets/images/products/Pote-de-Tabletes-de-Doce-de-Leite-Tradicional.png",
    },
    {
      name: "Doce de Leite com Coco 300 g",
      slug: "doce-de-leite-com-coco-300g",
      category: "Pastoso",
      size: "300 g",
      description: "Doce de leite cremoso com coco, perfeito para sobremesas e consumo em família.",
      image: "/assets/images/products/Mini-Doce-de-leite-com-Coco.png",
    },
    {
      name: "Cocada - Doce de Leite com Coco 300 g",
      slug: "cocada-doce-de-leite-com-coco-300g",
      category: "Pastoso",
      size: "300 g",
      description: "Cocada com doce de leite e coco em versão cremosa, com sabor brasileiro bem afetivo.",
      image: "/assets/images/products/Mini-Cocada-Doce-de-Leite-com-Coco-1.png",
    },
    {
      name: "Doce de Leite com Ameixa 300 g",
      slug: "doce-de-leite-com-ameixa-300g",
      category: "Pastoso",
      size: "300 g",
      description: "Doce de leite pastoso com ameixa, uma combinação clássica e equilibrada.",
      image: "/assets/images/products/Mini-Doce-de-Leite-com-Ameixa.png",
    },
    {
      name: "Doce de Leite Tradicional 300 g",
      slug: "doce-de-leite-tradicional-300g",
      category: "Pastoso",
      size: "300 g",
      description: "Doce de leite tradicional em pote de 300 g, cremoso e feito com receita mineira.",
      image: "/assets/images/products/Mini-Doce-de-Leite-Tradicional.png",
    },
    {
      name: "Doce de Leite com Ameixa Barra 400 g",
      slug: "doce-de-leite-com-ameixa-barra-400g",
      category: "Barra",
      size: "400 g",
      description: "Barra de doce de leite com ameixa, com textura firme e sabor intenso.",
      image: "/assets/images/products/Tablete-doce-de-Leite-com-Ameixa.png",
    },
    {
      name: "Cocada - Doce de Leite com Coco Barra 400 g",
      slug: "cocada-doce-de-leite-com-coco-barra-400g",
      category: "Barra",
      size: "400 g",
      description: "Tablete de cocada com doce de leite e coco, opção marcante para quem gosta de textura.",
      image: "/assets/images/products/Tablete-Cocada-Doce-de-Leite-com-Coco.png",
    },
    {
      name: "Doce de Leite com Amendoim Barra 400 g",
      slug: "doce-de-leite-com-amendoim-barra-400g",
      category: "Barra",
      size: "400 g",
      description: "Barra de doce de leite com amendoim, com sabor tostado e corte generoso.",
      image: "/assets/images/products/Tablete-Doce-de-Leite-com-Amendoim.png",
    },
    {
      name: "Doce de Leite Tradicional Barra 400 g",
      slug: "doce-de-leite-tradicional-barra-400g",
      category: "Barra",
      size: "400 g",
      description: "Barra tradicional de doce de leite mineiro, firme, cremosa ao paladar e cheia de memória.",
      image: "/assets/images/products/Tablete-doce-de-Leite-Tradicional-1.png",
    },
    {
      name: "Doce de Leite com Coco",
      slug: "doce-de-leite-com-coco",
      category: "Pastoso",
      size: "Pote familiar",
      description: "Versão pastosa com coco para quem busca um doce de leite mais aromático e especial.",
      image: "/assets/images/products/Doce-de-Leite-com-Coco-1.png",
    },
    {
      name: "Cocada - Doce de Leite com Coco",
      slug: "cocada-doce-de-leite-com-coco",
      category: "Pastoso",
      size: "Pote familiar",
      description: "Cocada cremosa com doce de leite e coco, com presença forte de sabor e textura.",
      image: "/assets/images/products/Doce-Pastoso-Doce-de-leite-com-Coco.png",
    },
    {
      name: "Doce de Leite com Ameixa",
      slug: "doce-de-leite-com-ameixa",
      category: "Pastoso",
      size: "Pote familiar",
      description: "Doce de leite com ameixa em versão pastosa, pensado para sobremesas e presentes.",
      image: "/assets/images/products/Doce-de-Leite-com-Ameixa.png",
    },
    {
      name: "Doce de Leite Tradicional",
      slug: "doce-de-leite-tradicional",
      category: "Pastoso",
      size: "Pote familiar",
      description: "O doce de leite tradicional da Doçura da Fazenda: cremoso, mineiro e artesanal.",
      image: "/assets/images/products/Doce-de-Leite-Tradicional.png",
    },
  ],
  reseller: {
    title: "Seja um revendedor",
    body:
      "A qualidade dos nossos produtos é reconhecida por consumidores de todo o Brasil, e toda a linha mantém o mesmo padrão de excelência. Estamos abertos a novas parcerias comerciais com lojistas, distribuidores e revendedores.",
  },
  gallery: [
    "/assets/images/emporio-1-1280x860-1.jpeg",
    "/assets/images/emporio-0-1280x860-1.jpeg",
    "/assets/images/3-1280x860-1.jpeg",
    "/assets/images/11-1280x860-1.jpeg",
  ],
  reviews: [
    {
      author: "Claudenir Aguiar",
      date: "05/04/2026",
      text: "Produtos excelentes e atendimento acolhedor.",
    },
    {
      author: "Soares Mauro",
      date: "26/03/2026",
      text:
        "Uma ótima parada para comprar produtos regionais como doces de leite, queijos e outras especialidades.",
    },
    {
      author: "Edson Scapinello",
      date: "20/03/2026",
      text: "Um espaço com muitas opções e atendimento atencioso durante toda a visita.",
    },
  ],
};

export type SiteData = typeof siteData;
