const nutritionDisclaimer =
  "*% Valores Diários de referência com base em uma dieta de 2.000kcal ou 8.400kJ. Seus valores diários podem ser maiores ou menores dependendo de suas necessidades energéticas. ** Valores Diários não estabelecidos.";

function createNutritionProfile(
  sourceUrl: string,
  packaging: string,
  serving: string,
  facts: Array<[label: string, value: string, dailyValue: string]>,
) {
  return {
    sourceUrl,
    packaging,
    serving,
    facts: facts.map(([label, value, dailyValue]) => ({
      label,
      value,
      dailyValue,
    })),
    disclaimer: nutritionDisclaimer,
  };
}

const nutritionProfiles = {
  displayAmeixa1kg: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-display-de-tabletes-ameixa-1-kg/",
    "Contém 40 unidades de 25g. 10 displays por caixa.",
    "Porção de 25g (1 unidade)",
    [
      ["Valores Energéticos", "118kcal / 492kJ", "6%"],
      ["Carboidratos", "22g", "7%"],
      ["Proteínas", "2,4g", "3%"],
      ["Gorduras Totais", "2,1g", "4%"],
      ["Gorduras Saturadas", "1,6g", "7%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "35mg", "1%"],
    ],
  ),
  displayCocada1kg: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-display-de-tabletes-coco-cocada-1-kg/",
    "Contém 40 unidades de 25g. 10 displays por caixa.",
    "Porção de 25g (1 unidade)",
    [
      ["Valores Energéticos", "118kcal / 492kJ", "6%"],
      ["Carboidratos", "22g", "7%"],
      ["Proteínas", "2,4g", "3%"],
      ["Gorduras Totais", "2,1g", "4%"],
      ["Gorduras Saturadas", "1,6g", "7%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "35mg", "1%"],
    ],
  ),
  displayAmendoim1kg: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-display-de-tabletes-amendoim-1kg/",
    "Contém 40 unidades de 25g. 10 displays por caixa.",
    "Porção de 25g (1 unidade)",
    [
      ["Valores Energéticos", "120kcal / 502kJ", "6%"],
      ["Carboidratos", "22g", "7%"],
      ["Proteínas", "2,3g", "3%"],
      ["Gorduras Totais", "2,6g", "5%"],
      ["Gorduras Saturadas", "2,1g", "10%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "38mg", "2%"],
    ],
  ),
  displayTradicional1kg: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-display-de-tabletes-tradicional-1kg/",
    "Contém 40 unidades de 25g. 10 displays por caixa.",
    "Porção de 25g (1 unidade)",
    [
      ["Valores Energéticos", "118kcal / 492kJ", "6%"],
      ["Carboidratos", "22g", "7%"],
      ["Proteínas", "2,4g", "3%"],
      ["Gorduras Totais", "2,1g", "4%"],
      ["Gorduras Saturadas", "1,6g", "7%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "35mg", "1%"],
    ],
  ),
  poteCocada: createNutritionProfile(
    "https://docuradafazenda.com.br/cocada-doce-de-leite-com-coco-em-tabletes-1-265kg-e-1-100kg/",
    "Linha em tabletes com pote plástico de 20 ou 23 unidades. 6 unidades por caixa.",
    "Porção de 55g (1 unidade)",
    [
      ["Valores Energéticos", "220kcal / 921kJ", "11%"],
      ["Carboidratos", "42g", "14%"],
      ["Proteínas", "3,9g", "5%"],
      ["Gorduras Totais", "4,2g", "8%"],
      ["Gorduras Saturadas", "3,6g", "17%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0,7g", "3%"],
      ["Sódio", "53mg", "2%"],
    ],
  ),
  poteAmendoim: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tabletes-com-amendoim-1-250kg-e-1-010kg/",
    "Pote plástico com 20 unidades em tabletes. 6 unidades por caixa.",
    "Porção de 50g (1 unidade)",
    [
      ["Valores Energéticos", "203kcal / 847kJ", "10%"],
      ["Carboidratos", "37g", "12%"],
      ["Proteínas", "3,7g", "5%"],
      ["Gorduras Totais", "4,4g", "8%"],
      ["Gorduras Saturadas", "2,5g", "11%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0,5g", "2%"],
      ["Sódio", "66mg", "3%"],
    ],
  ),
  poteAmeixa: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tabletes-com-ameixa-1-250kg-e-1-010kg/",
    "Pote plástico com 20 unidades em tabletes. 6 unidades por caixa.",
    "Porção de 50g (1 unidade)",
    [
      ["Valores Energéticos", "202kcal / 845kJ", "10%"],
      ["Carboidratos", "37g", "12%"],
      ["Proteínas", "4,0g", "5%"],
      ["Gorduras Totais", "4,2g", "8%"],
      ["Gorduras Saturadas", "3,2g", "14%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "69mg", "3%"],
    ],
  ),
  poteTradicional: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tabletes-tradicional-1-250kg-e-1-010kg/",
    "Pote plástico com 20 unidades em tabletes. 6 unidades por caixa.",
    "Porção de 50g (1 unidade)",
    [
      ["Valores Energéticos", "196kcal / 819kJ", "10%"],
      ["Carboidratos", "38g", "13%"],
      ["Proteínas", "3,5g", "5%"],
      ["Gorduras Totais", "3,3g", "6%"],
      ["Gorduras Saturadas", "2,4g", "11%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "65mg", "3%"],
    ],
  ),
  pastosoCoco: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-com-coco-680g-e-300g/",
    "Pastoso 680g: 15 unidades por caixa. Pastoso 300g: 24 unidades por caixa.",
    "Porção de 20g (1 colher de sopa)",
    [
      ["Valores Energéticos", "62kcal / 261kJ", "3%"],
      ["Carboidratos", "11g", "4%"],
      ["Proteínas", "1,5g", "2%"],
      ["Gorduras Totais", "1,8g", "3%"],
      ["Gorduras Saturadas", "1,5g", "7%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0,7g", "3%"],
      ["Sódio", "29mg", "1%"],
    ],
  ),
  pastosoCocada: createNutritionProfile(
    "https://docuradafazenda.com.br/cocada-doce-de-leite-com-coco-680g/",
    "Pastoso 680g: 15 unidades por caixa. Pastoso 300g: 24 unidades por caixa.",
    "Porção de 20g (1 colher de sopa)",
    [
      ["Valores Energéticos", "62kcal / 261kJ", "3%"],
      ["Carboidratos", "11g", "4%"],
      ["Proteínas", "2,8g", "4%"],
      ["Gorduras Totais", "1,4g", "3%"],
      ["Gorduras Saturadas", "1,1g", "5%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "26mg", "1%"],
    ],
  ),
  pastosoAmeixa: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-com-ameixa-680g-e-300g/",
    "Pastoso 680g: 15 unidades por caixa. Pastoso 300g: 24 unidades por caixa.",
    "Porção de 20g (1 colher de sopa)",
    [
      ["Valores Energéticos", "62kcal / 261kJ", "3%"],
      ["Carboidratos", "12g", "4%"],
      ["Proteínas", "1,3g", "2%"],
      ["Gorduras Totais", "1,3g", "2%"],
      ["Gorduras Saturadas", "0,8g", "4%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "1%"],
      ["Sódio", "26mg", "1%"],
    ],
  ),
  pastosoTradicional: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-tradicional-680g-e-300g/",
    "Pastoso 680g: 15 unidades por caixa. Pastoso 300g: 24 unidades por caixa.",
    "Porção de 20g (1 colher de sopa)",
    [
      ["Valores Energéticos", "62kcal / 261kJ", "3%"],
      ["Carboidratos", "12g", "4%"],
      ["Proteínas", "1,0g", "1%"],
      ["Gorduras Totais", "1,3g", "2%"],
      ["Gorduras Saturadas", "0,9g", "4%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "26mg", "1%"],
    ],
  ),
  barraAmeixa400g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-ameixa-barra/",
    "Contém 400g. 32 unidades por caixa.",
    "Porção de 50g (1 fatia)",
    [
      ["Valores Energéticos", "202kcal / 845kJ", "10%"],
      ["Carboidratos", "37g", "12%"],
      ["Proteínas", "4,0g", "5%"],
      ["Gorduras Totais", "4,2g", "8%"],
      ["Gorduras Saturadas", "3,2g", "14%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "69mg", "3%"],
    ],
  ),
  barraCocada400g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-cocada-barra/",
    "Contém 400g. 32 unidades por caixa.",
    "Porção de 25g",
    [
      ["Valores Energéticos", "118kcal / 492kJ", "6%"],
      ["Carboidratos", "22g", "7%"],
      ["Proteínas", "2,4g", "3%"],
      ["Gorduras Totais", "2,1g", "4%"],
      ["Gorduras Saturadas", "1,6g", "7%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "35mg", "1%"],
    ],
  ),
  barraAmendoim400g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-amendoim-barra/",
    "Contém 400g. 32 unidades por caixa.",
    "Porção de 50g (1 fatia)",
    [
      ["Valores Energéticos", "203kcal / 847kJ", "10%"],
      ["Carboidratos", "37g", "12%"],
      ["Proteínas", "3,7g", "5%"],
      ["Gorduras Totais", "4,4g", "8%"],
      ["Gorduras Saturadas", "2,5g", "11%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0,5g", "2%"],
      ["Sódio", "66mg", "3%"],
    ],
  ),
  barraTradicional400g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-tradicional-em-barra/",
    "Contém 400g. 32 unidades por caixa.",
    "Porção de 50g (1 fatia)",
    [
      ["Valores Energéticos", "196kcal / 819kJ", "10%"],
      ["Carboidratos", "38g", "13%"],
      ["Proteínas", "3,5g", "5%"],
      ["Gorduras Totais", "3,3g", "6%"],
      ["Gorduras Saturadas", "2,4g", "11%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "65mg", "3%"],
    ],
  ),
  tableteAmeixa200g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tabletes-com-ameixa-250g-e-200g/",
    "Tabletes saquinho 200g. 40 unidades por caixa.",
    "Porção de 50g (5 unidades)",
    [
      ["Valores Energéticos", "202kcal / 845kJ", "10%"],
      ["Carboidratos", "37g", "12%"],
      ["Proteínas", "4,0g", "5%"],
      ["Gorduras Totais", "4,2g", "8%"],
      ["Gorduras Saturadas", "3,2g", "14%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "69mg", "3%"],
    ],
  ),
  tableteCoco200g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tabletes-com-coco-250g-e-200g/",
    "Tabletes saquinho 200g. 40 unidades por caixa.",
    "Porção de 50g (5 unidades)",
    [
      ["Valores Energéticos", "196kcal / 821kJ", "10%"],
      ["Carboidratos", "38g", "13%"],
      ["Proteínas", "3,9g", "5%"],
      ["Gorduras Totais", "3,3g", "6%"],
      ["Gorduras Saturadas", "2,2g", "10%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "1%"],
      ["Sódio", "72mg", "3%"],
    ],
  ),
  tableteTradicional200g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tabletes-tradicional-250g-e-200g/",
    "Tabletes saquinho 200g. 40 unidades por caixa.",
    "Porção de 50g (5 unidades)",
    [
      ["Valores Energéticos", "196kcal / 819kJ", "10%"],
      ["Carboidratos", "38g", "13%"],
      ["Proteínas", "3,5g", "5%"],
      ["Gorduras Totais", "3,3g", "6%"],
      ["Gorduras Saturadas", "2,4g", "11%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "65mg", "3%"],
    ],
  ),
  tableteAmendoim200g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tabletes-com-amendoim-250g-e-200g/",
    "Tabletes saquinho 200g. 40 unidades por caixa.",
    "Porção de 50g (5 unidades)",
    [
      ["Valores Energéticos", "203kcal / 847kJ", "10%"],
      ["Carboidratos", "37g", "12%"],
      ["Proteínas", "3,7g", "5%"],
      ["Gorduras Totais", "4,4g", "8%"],
      ["Gorduras Saturadas", "2,5g", "11%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0,5g", "2%"],
      ["Sódio", "66mg", "3%"],
    ],
  ),
  tableteCocada200g: createNutritionProfile(
    "https://docuradafazenda.com.br/cocada-doce-de-leite-em-tabletes-com-coco-250g-e-200g/",
    "Tabletes saquinho 200g. 40 unidades por caixa.",
    "Porção de 50g (5 unidades)",
    [
      ["Valores Energéticos", "198kcal / 830kJ", "10%"],
      ["Carboidratos", "38g", "13%"],
      ["Proteínas", "4,8g", "6%"],
      ["Gorduras Totais", "3,3g", "6%"],
      ["Gorduras Saturadas", "2,4g", "11%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "2%"],
      ["Sódio", "55mg", "2%"],
    ],
  ),
  tableteCasadinho200g: createNutritionProfile(
    "https://docuradafazenda.com.br/casadinho-doce-de-leite-com-chocolate-em-tabletes-250g-e-200g/",
    "Tabletes saquinho 200g. 40 unidades por caixa.",
    "Porção de 50g (5 unidades)",
    [
      ["Valores Energéticos", "204kcal / 853kJ", "10%"],
      ["Carboidratos", "38g", "13%"],
      ["Proteínas", "3,3g", "4%"],
      ["Gorduras Totais", "4,3g", "8%"],
      ["Gorduras Saturadas", "3,7g", "17%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "80mg", "3%"],
    ],
  ),
  sortidos1100g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-sortidos-em-tabletes-1-100kg/",
    "Pote plástico com 20 unidades de 55g. 6 unidades por caixa.",
    "Porção de 55g (1 unidade)",
    [
      ["Valores Energéticos", "218kcal / 914kJ", "11%"],
      ["Carboidratos", "45g", "15%"],
      ["Proteínas", "2,5g", "3%"],
      ["Gorduras Totais", "3,4g", "6%"],
      ["Gorduras Saturadas", "2,3g", "10%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0,0g", "0%"],
      ["Sódio", "63mg", "3%"],
    ],
  ),
  cocada1100g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-cocada-1-100kg/",
    "Pote plástico com 20 unidades de 55g. 6 unidades por caixa.",
    "Porção de 55g (1 unidade)",
    [
      ["Valores Energéticos", "218kcal / 914kJ", "11%"],
      ["Carboidratos", "45g", "15%"],
      ["Proteínas", "2,5g", "3%"],
      ["Gorduras Totais", "3,4g", "6%"],
      ["Gorduras Saturadas", "2,3g", "10%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0,0g", "0%"],
      ["Sódio", "63mg", "3%"],
    ],
  ),
  tablete65g: createNutritionProfile(
    "https://docuradafazenda.com.br/doce-de-leite-em-tablete/",
    "Contém 1 unidade de 65g.",
    "Porção de 65g (1 unidade)",
    [
      ["Valores Energéticos", "118kcal / 492kJ", "6%"],
      ["Carboidratos", "22g", "7%"],
      ["Proteínas", "2,4g", "3%"],
      ["Gorduras Totais", "2,1g", "4%"],
      ["Gorduras Saturadas", "1,6g", "7%"],
      ["Gorduras Trans", "0g", "**"],
      ["Fibra Alimentar", "0g", "0%"],
      ["Sódio", "35mg", "1%"],
    ],
  ),
} as const;

export const siteData = {
  brand: "Doçura da Fazenda",
  location: "Cambuí, Minas Gerais",
  whatsappLabel: "Fale conosco",
  whatsappUrl: "https://wa.me/553534316838",
  instagramUrl: "https://www.instagram.com/docuradafazenda_oficial/",
  phone: "(35) 3431-6838",
  email: "Atendimento pelo WhatsApp",
  address: "Rod. Fernão Dias, 894, Cambuí - MG, 37600-000",
  googleReviewsUrl: "https://share.google/7ij1AE1TOkFROQFw1",
  mapEmbed:
    "https://maps.google.com/maps?q=Emp%C3%B3rio%20-%20Do%C3%A7ura%20Da%20Fazenda%2C%20Rod.%20Fern%C3%A3o%20Dias%2C%20894%2C%20Cambu%C3%AD%20-%20MG%2C%2037600-000&t=m&z=15&output=embed&iwloc=near",
  nav: [
    { label: "Início", href: "/" },
    { label: "Produtos", href: "/produtos" },
    { label: "Sobre nós", href: "/sobre-nos" },
    { label: "Contato", href: "/contato" },
  ],
  heroSlides: [
    {
      title: "O verdadeiro sabor do doce de leite mineiro",
      body:
        "Uma receita de família feita com paciência, tradição e ingredientes selecionados com cuidado.",
      video: "/assets/videos/bg-principal-1-com-vaquinha.mp4",
    },
    {
      title: "Sabor que carrega tradição",
      body:
        "Cada produção preserva a textura marcante e o sabor inconfundível do autêntico doce de leite artesanal.",
      video: "/assets/videos/bg-principal-1-com-vaquinha.mp4",
    },
  ],
  heroBanners: [
    {
      eyebrow: "Desde 1998 • Cambuí, Minas Gerais",
      title: "O verdadeiro sabor do doce de leite mineiro.",
      mobileTitle: "Doçura da Fazenda",
      body:
        "Produção familiar, textura cremosa e ingredientes selecionados para preservar o sabor autêntico que acompanha a mesa mineira.",
      mobileBody:
        "Doce de leite mineiro, produção familiar e textura cremosa desde 1998.",
      cta: "Conheça os produtos",
      href: "/produtos",
      mediaType: "image",
      media: "/assets/images/banner-web.png",
      fallback: "/assets/images/banner-web.png",
      product: "/assets/images/img-docepastoso.png",
    },
    {
      eyebrow: "Receita tradicional",
      title: "Sabor que carrega tradição.",
      mobileTitle: "Sabor mineiro de verdade",
      body:
        "Tabletes, doces de leite pastosos e barras feitos com cuidado artesanal e padrão de qualidade para todos os momentos.",
      mobileBody:
        "Tabletes, pastosos e barras feitos com cuidado artesanal em Cambuí.",
      cta: "Ver linha completa",
      href: "/produtos",
      mediaType: "video",
      media: "/assets/videos/bg-principal-2.mp4",
      fallback: "/assets/images/emporio/emporio-atual-02.jpg",
      product: "/assets/images/caramelo.png",
    },
    {
      eyebrow: "Empório em Cambuí",
      title: "Uma parada mineira na Fernão Dias.",
      mobileTitle: "Empório em Cambuí",
      body:
        "Além dos doces, o empório reúne produtos regionais e atendimento acolhedor às margens da Rodovia Fernão Dias.",
      mobileBody:
        "Doces, produtos regionais e atendimento acolhedor na Fernão Dias.",
      cta: "Nossa localização",
      href: "/contato",
      mediaType: "video",
      media: "/assets/videos/bg-principal-1-com-vaquinha.mp4",
      fallback: "/assets/images/emporio/emporio-atual-04.jpg",
      product: "/assets/images/caramelo-macchiato.png",
    },
  ],
  about: {
    eyebrow: "Sobre nós",
    title: "Uma história de família, tradição e evolução constante",
    body:
      "A Doçura da Fazenda nasceu em 1998, em Cambuí, pelas mãos de quatro irmãos no bairro Nunes de Cima. O que começou como uma produção familiar cresceu sem perder a essência artesanal, levando para cada embalagem o sabor tradicional do doce de leite mineiro e o cuidado de uma empresa feita com orgulho da própria origem.",
    bullets: [
      "Fundada em 1998 por 4 irmãos na zona rural de Cambuí, no sul de Minas Gerais.",
      "Nova estrutura às margens da Fernão Dias desde 2015, com fábrica e empório no mesmo endereço.",
      "Produtos com S.I.F. e produção alinhada às normas do Ministério da Agricultura.",
      "Mais de duas décadas combinando sabor artesanal, padrão e confiança comercial.",
    ],
    milestones: [
      {
        label: "Fundação",
        value: "1998",
        detail: "Início da produção familiar no bairro Nunes de Cima.",
      },
      {
        label: "Nova fase",
        value: "2015",
        detail: "Mudança para a Fernão Dias com estrutura maior e mais completa.",
      },
      {
        label: "Qualidade",
        value: "S.I.F.",
        detail: "Produção sob inspeção federal e padrões do Ministério da Agricultura.",
      },
    ],
    featureImage: "/assets/images/emporio/emporio-atual-01.jpg",
    pillars: [
      {
        title: "Receita tradicional",
        body: "O autêntico doce de leite mineiro feito com história, cuidado e dedicação.",
        image: "/assets/images/receita.png",
      },
      {
        title: "Melhores ingredientes",
        body: "Matérias-primas escolhidas com cuidado para garantir mais sabor e qualidade.",
        image: "/assets/images/farinha.png",
      },
      {
        title: "Sabor que encanta",
        body: "Um doce de leite marcante, feito para conquistar todos os paladares.",
        image: "/assets/images/caramelo.png",
      },
      {
        title: "Preparado com carinho",
        body: "Mais do que um produto, um sabor especial feito para criar boas memórias.",
        image: "/assets/images/caramelo-macchiato.png",
      },
    ],
  },
  productsIntro: {
    title: "Conheça a nossa linha de produtos",
    body:
      "Tabletes, doce de leite pastoso, barras e versões sortidas produzidos com qualidade, tradição e o verdadeiro sabor mineiro.",
  },
  productCategories: [
    {
      name: "Tabletes",
      slug: "tablete",
      description: "Produtos de 65g, 200g e displays para venda unitária e ponto de venda.",
      image: "/assets/images/products/novo-espeto-tablete-tradicional.png",
    },
    {
      name: "Pastosos",
      slug: "pastoso",
      description: "Potes de 680g e 300g para revenda, consumo e uso em receitas.",
      image: "/assets/images/products/novo-pastoso-tradicional-680g.png",
    },
    {
      name: "Barras",
      slug: "barra",
      description: "Barras de 400g com sabores tradicionais e combinações especiais.",
      image: "/assets/images/products/novo-barra-tradicional-400g.png",
    },
    {
      name: "Kits e Displays",
      slug: "kits-displays",
      description: "Caixas fechadas, potes e displays prontos para lojistas.",
      image: "/assets/images/products/novo-pote-sortido-20un.png",
    },
  ],
  products: [
    {
      name: "Display de Doce de Leite com Ameixa 1kg",
      slug: "display-de-doce-de-leite-com-ameixa-1-kg",
      category: "Display",
      size: "1kg",
      description: "Display com doce de leite e ameixa, pensado para exposição, venda assistida e giro no balcão.",
      image: "/assets/images/products/novo-display-ameixa.png",
      nutrition: nutritionProfiles.displayAmeixa1kg,
    },
    {
      name: "Display Cocada - Doce de Leite com Coco 1kg",
      slug: "display-cocada-doce-de-leite-com-coco-1-kg",
      category: "Display",
      size: "1kg",
      description: "Display de cocada com doce de leite e coco, com sabor marcante para revendas e empórios.",
      image: "/assets/images/products/novo-display-cocada.png",
      nutrition: nutritionProfiles.displayCocada1kg,
    },
    {
      name: "Display de Doce de Leite com Amendoim 1kg",
      slug: "display-de-doce-de-leite-com-amendoim-1-kg",
      category: "Display",
      size: "1kg",
      description: "Display de doce de leite com amendoim, uma opção de venda prática e cheia de textura.",
      image: "/assets/images/products/novo-display-amendoim.png",
      nutrition: nutritionProfiles.displayAmendoim1kg,
    },
    {
      name: "Display de Doce de Leite Tradicional 1kg",
      slug: "display-de-doce-de-leite-tradicional-1-kg",
      category: "Display",
      size: "1kg",
      description: "Display tradicional com o sabor clássico do doce de leite mineiro para ponto de venda.",
      image: "/assets/images/products/novo-display-tradicional.png",
      nutrition: nutritionProfiles.displayTradicional1kg,
    },
    {
      name: "Potes Cocada - Doce de Leite com Coco c/20 un. 50g",
      slug: "potes-cocada-doce-de-leite-com-coco-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50g",
      description: "Pote com tabletes individuais de cocada com doce de leite e coco, ideal para revenda.",
      image: "/assets/images/products/novo-pote-cocada-20un.png",
      nutrition: nutritionProfiles.poteCocada,
    },
    {
      name: "Potes Doce de Leite com Amendoim c/20 un. 50g",
      slug: "potes-doce-de-leite-com-amendoim-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50g",
      description: "Pote com unidades individuais de doce de leite com amendoim para balcões e empórios.",
      image: "/assets/images/products/novo-pote-amendoim-20un.png",
      nutrition: nutritionProfiles.poteAmendoim,
    },
    {
      name: "Potes Doce de Leite com Ameixa c/20 un. 50g",
      slug: "potes-doce-de-leite-com-ameixa-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50g",
      description: "Pote com tabletes de doce de leite com ameixa em porções individuais.",
      image: "/assets/images/products/novo-pote-ameixa-20un.png",
      nutrition: nutritionProfiles.poteAmeixa,
    },
    {
      name: "Pote Doce de Leite Tradicional c/20 un. 50g",
      slug: "pote-doce-de-leite-tradicional-c-20-uni-50g",
      category: "Display",
      size: "20 un. de 50g",
      description: "Pote com tabletes tradicionais de doce de leite, prontos para exposição e revenda.",
      image: "/assets/images/products/novo-pote-tradicional-20un.png",
      nutrition: nutritionProfiles.poteTradicional,
    },
    {
      name: "Doce de Leite com Coco 300g",
      slug: "doce-de-leite-com-coco-300g",
      category: "Pastoso",
      size: "300g",
      description: "Doce de leite cremoso com coco, perfeito para sobremesas e consumo em família.",
      image: "/assets/images/products/novo-pastoso-coco-300g.png",
      nutrition: nutritionProfiles.pastosoCoco,
    },
    {
      name: "Cocada - Doce de Leite com Coco 300g",
      slug: "cocada-doce-de-leite-com-coco-300g",
      category: "Pastoso",
      size: "300g",
      description: "Cocada com doce de leite e coco em versão cremosa, com sabor brasileiro bem afetivo.",
      image: "/assets/images/products/novo-pastoso-cocada-300g.png",
      nutrition: nutritionProfiles.pastosoCocada,
    },
    {
      name: "Doce de Leite com Ameixa 300g",
      slug: "doce-de-leite-com-ameixa-300g",
      category: "Pastoso",
      size: "300g",
      description: "Doce de leite pastoso com ameixa, uma combinação clássica e equilibrada.",
      image: "/assets/images/products/novo-pastoso-ameixa-300g.png",
      nutrition: nutritionProfiles.pastosoAmeixa,
    },
    {
      name: "Doce de Leite Tradicional 300g",
      slug: "doce-de-leite-tradicional-300g",
      category: "Pastoso",
      size: "300g",
      description: "Doce de leite tradicional em pote de 300g, cremoso e feito com receita mineira.",
      image: "/assets/images/products/novo-pastoso-tradicional-300g.png",
      nutrition: nutritionProfiles.pastosoTradicional,
    },
    {
      name: "Doce de Leite com Ameixa Barra 400g",
      slug: "doce-de-leite-com-ameixa-barra-400g",
      category: "Barra",
      size: "400g",
      description: "Barra de doce de leite com ameixa, com textura firme e sabor intenso.",
      image: "/assets/images/products/novo-barra-ameixa-400g.png",
      nutrition: nutritionProfiles.barraAmeixa400g,
    },
    {
      name: "Cocada - Doce de Leite com Coco Barra 400g",
      slug: "cocada-doce-de-leite-com-coco-barra-400g",
      category: "Barra",
      size: "400g",
      description: "Tablete de cocada com doce de leite e coco, opção marcante para quem gosta de textura.",
      image: "/assets/images/products/novo-barra-cocada-400g.png",
      nutrition: nutritionProfiles.barraCocada400g,
    },
    {
      name: "Doce de Leite com Amendoim Barra 400g",
      slug: "doce-de-leite-com-amendoim-barra-400g",
      category: "Barra",
      size: "400g",
      description: "Barra de doce de leite com amendoim, com sabor tostado e corte generoso.",
      image: "/assets/images/products/novo-barra-amendoim-400g.png",
      nutrition: nutritionProfiles.barraAmendoim400g,
    },
    {
      name: "Doce de Leite Tradicional Barra 400g",
      slug: "doce-de-leite-tradicional-barra-400g",
      category: "Barra",
      size: "400g",
      description: "Barra tradicional de doce de leite mineiro, firme, cremosa ao paladar e cheia de memória.",
      image: "/assets/images/products/novo-barra-tradicional-400g.png",
      nutrition: nutritionProfiles.barraTradicional400g,
    },
    {
      name: "Doce de Leite com Ameixa em Tabletes 200g",
      slug: "doce-de-leite-com-ameixa-em-tabletes-200g",
      category: "Tablete",
      size: "200g",
      description: "Saquinho com tabletes de doce de leite e ameixa, ideal para consumo em pequenas porções ou revenda.",
      image: "https://docuradafazenda.com.br/wp-content/uploads/2024/03/Ameixa-200g-FD.png",
      nutrition: nutritionProfiles.tableteAmeixa200g,
    },
    {
      name: "Doce de Leite com Coco em Tabletes 200g",
      slug: "doce-de-leite-com-coco-em-tabletes-200g",
      category: "Tablete",
      size: "200g",
      description: "Tabletes de doce de leite com coco em embalagem prática, com sabor marcante e textura macia.",
      image: "https://docuradafazenda.com.br/wp-content/uploads/2024/03/Coco-200g-FD.png",
      nutrition: nutritionProfiles.tableteCoco200g,
    },
    {
      name: "Doce de Leite Tradicional em Tabletes 200g",
      slug: "doce-de-leite-tradicional-em-tabletes-200g",
      category: "Tablete",
      size: "200g",
      description: "Versão tradicional em tabletes, pensada para porções menores e consumo prático no dia a dia.",
      image:
        "https://docuradafazenda.com.br/wp-content/uploads/2024/03/Photoroom_20240313_170318-e1710360368129.jpg",
      nutrition: nutritionProfiles.tableteTradicional200g,
    },
    {
      name: "Doce de Leite com Amendoim em Tabletes 200g",
      slug: "doce-de-leite-com-amendoim-em-tabletes-200g",
      category: "Tablete",
      size: "200g",
      description: "Tabletes de doce de leite com amendoim para quem busca uma combinação mais intensa e crocante.",
      image:
        "https://docuradafazenda.com.br/wp-content/uploads/2024/03/Photoroom_20240313_170224-e1710360539484.png",
      nutrition: nutritionProfiles.tableteAmendoim200g,
    },
    {
      name: "Cocada - Doce de Leite com Coco em Tabletes 200g",
      slug: "cocada-doce-de-leite-com-coco-em-tabletes-200g",
      category: "Tablete",
      size: "200g",
      description: "Cocada em tabletes com doce de leite e coco, em versão prática para presente, balcão ou consumo individual.",
      image:
        "https://docuradafazenda.com.br/wp-content/uploads/2024/03/Photoroom_20240312_101010-e1710359714747.png",
      nutrition: nutritionProfiles.tableteCocada200g,
    },
    {
      name: "Casadinho de Doce de Leite com Chocolate em Tabletes 200g",
      slug: "casadinho-de-doce-de-leite-com-chocolate-em-tabletes-200g",
      category: "Tablete",
      size: "200g",
      description: "Casadinho em tabletes com doce de leite e chocolate, trazendo uma combinação mais indulgente para a linha.",
      image: "https://docuradafazenda.com.br/wp-content/uploads/2024/03/Chocolate-200g.png",
      nutrition: nutritionProfiles.tableteCasadinho200g,
    },
    {
      name: "Doce de Leite em Tablete 65g",
      slug: "doce-de-leite-em-tablete-65g",
      category: "Tablete",
      size: "65g",
      description: "Tablete unitário de 65g, prático para consumo imediato, lembranças e venda por unidade.",
      image: "/assets/images/products/novo-espeto-tablete-tradicional.png",
      nutrition: nutritionProfiles.tablete65g,
    },
    {
      name: "Doce de Leite com Coco",
      slug: "doce-de-leite-com-coco",
      category: "Pastoso",
      size: "Pote familiar",
      description: "Versão pastosa com coco para quem busca um doce de leite mais aromático e especial.",
      image: "/assets/images/products/novo-pastoso-coco-680g.png",
      nutrition: nutritionProfiles.pastosoCoco,
    },
    {
      name: "Cocada - Doce de Leite com Coco",
      slug: "cocada-doce-de-leite-com-coco",
      category: "Pastoso",
      size: "Pote familiar",
      description: "Cocada cremosa com doce de leite e coco, com presença forte de sabor e textura.",
      image: "/assets/images/products/novo-pastoso-cocada-680g.png",
      nutrition: nutritionProfiles.pastosoCocada,
    },
    {
      name: "Doce de Leite com Ameixa",
      slug: "doce-de-leite-com-ameixa",
      category: "Pastoso",
      size: "Pote familiar",
      description: "Doce de leite com ameixa em versão pastosa, pensado para sobremesas e presentes.",
      image: "/assets/images/products/novo-pastoso-ameixa-680g.png",
      nutrition: nutritionProfiles.pastosoAmeixa,
    },
    {
      name: "Doce de Leite Tradicional",
      slug: "doce-de-leite-tradicional",
      category: "Pastoso",
      size: "Pote familiar",
      description: "O doce de leite tradicional da Doçura da Fazenda: cremoso, mineiro e artesanal.",
      image: "/assets/images/products/novo-pastoso-tradicional-680g.png",
      nutrition: nutritionProfiles.pastosoTradicional,
    },
    {
      name: "Doce de Leite Sortidos em Tabletes 1,100kg",
      slug: "doce-de-leite-sortidos-em-tabletes-1-100kg",
      category: "Display",
      size: "1,100kg",
      description: "Pote sortido com unidades em tabletes, pensado para exposição e venda com variedade de sabores.",
      image: "/assets/images/products/novo-pote-sortido-20un.png",
      nutrition: nutritionProfiles.sortidos1100g,
    },
    {
      name: "Doce de Leite com Cocada 1,100kg",
      slug: "doce-de-leite-com-cocada-1-100kg",
      category: "Display",
      size: "1,100kg",
      description: "Pote plástico com unidades de doce de leite com cocada, ideal para balcão e pontos de venda com alto giro.",
      image: "/assets/images/products/novo-pote-cocada-20un.png",
      nutrition: nutritionProfiles.cocada1100g,
    },
  ],
  reseller: {
    title: "Conheça nosso empório na Fernão Dias",
    body:
      "Uma parada completa em Cambuí para comprar doces da fábrica, produtos regionais, queijos, cafés, lembranças mineiras e presentes. Visite a loja, prove o sabor da Doçura da Fazenda e leve um pouco de Minas com você.",
  },
  gallery: [
    {
      src: "/assets/images/emporio/emporio-atual-02.jpg",
      alt: "Bancada central do empório com potes, barras e doces embalados da Doçura da Fazenda",
    },
    {
      src: "/assets/images/emporio/emporio-atual-03.jpg",
      alt: "Prateleira central do empório com doces de leite, tabletes e potes organizados",
    },
    {
      src: "/assets/images/emporio/emporio-atual-04.jpg",
      alt: "Vista ampla do empório com expositores de doces e produtos regionais",
    },
    {
      src: "/assets/images/emporio/emporio-atual-01.jpg",
      alt: "Prateleiras laterais do empório com biscoitos, doces e conservas regionais",
    },
    {
      src: "/assets/images/emporio/emporio-atual-05.jpg",
      alt: "Área de frios e laticínios do empório com vitrines refrigeradas",
    },
    {
      src: "/assets/images/emporio/emporio-atual-06.jpg",
      alt: "Expositor de bebidas, cachaças e produtos artesanais no empório",
    },
    {
      src: "/assets/images/emporio/emporio-atual-07.jpg",
      alt: "Prateleira de presentes e artesanato regional dentro do empório",
    },
    {
      src: "/assets/images/emporio/emporio-atual-08.jpg",
      alt: "Expositor de suspiros, artesanato e lembranças mineiras no empório",
    },
    {
      src: "/assets/images/emporio/emporio-atual-09.jpg",
      alt: "Detalhe de doces e mel em expositor de madeira dentro do empório",
    },
  ],
};

export type SiteData = typeof siteData;
